DROP TABLE IF EXISTS food_orders CASCADE;

CREATE TABLE food_orders (
  id SERIAL PRIMARY KEY NOT NULL,
  food_id INTEGER NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL
);
